--- 
- name: Create VLAN 100
  hosts: cisco
  gather_facts: no

  tasks: 
    - name: Create vlan
      cisco.ios.ios_vlan:
        vlan_id: 100
        name: test-vlan
        state: present

    - name: Display all VLANs
      cisco.ios.ios_command:
        commands:
          - "show vlan brief"
      register: vlan_output

    - name: Print VLAN output
      debug:
        var: vlan_output.stdout